### ISSUE TITLE
How to use it at Microsoft Power BI

### ISSUE THREAD

**Issue by paulofernando1512** [DiaAzul/powerBI-visual-PopPyramid3#2]
Please I'm new on Power BI and GitHub. So how could I use this template inside Microsoft Power BI? Or, how to create a .pbiviz file to import?
Regards
Paulo

**Comment by DiaAzul** [comment]
My apologies for the very late response - I didn't receive a notification that an issue had been raised.
The pbviz files are on the documentation page at : https://diaazul.github.io/
You can download the latest version from there.
