### ISSUE TITLE
Doesn't show data

### ISSUE THREAD

**Issue by JenskeM** [DiaAzul/powerBI-visual-PopPyramid3#3]
Dear DiaAzul,

Your visual looks beautiful, so I would love to use it in my dashboard. But the only thing is, when I import it and put my data in it, the visual stays blank. I also used your sample data and tried it with that. But unfortunately it stays blank with that as well. Can you please tell me what I do wrong?

![Screenshot_3](https://user-images.githubusercontent.com/69784332/90362439-ef084400-e060-11ea-9c3b-9fb633d51d4f.png)

Thank you in advance!

Kind regards,

Jenske

**Comment by Intel2022** [comment]
I am also having the same issue - the visual stays blank despite putting in the data.   Were you able to get a resolution? Kindly let me know.

**Comment by DiaAzul** [comment]
Thank you for your comments. I have updated the sample data and included documentation describing how to use the sample data in PowerBI desktop.

https://github.com/DiaAzul/powerBI-visual-PopPyramid3/tree/master/sampleData
